# Generated by Django 4.0.6 on 2022-07-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_available', '0001_initial'),
        ('users', '0005_alter_student_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, to='courses_available.courses'),
        ),
    ]
