# Generated by Django 4.0.6 on 2022-07-26 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_instructor_course_instructor_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='courses',
            new_name='course',
        ),
    ]
