# Generated by Django 4.0.6 on 2022-07-26 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_courses_instructor_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='course',
            new_name='courses',
        ),
    ]
