# Generated by Django 4.0.6 on 2022-07-29 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_available', '0001_initial'),
        ('users', '0012_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='courses',
        ),
        migrations.AddField(
            model_name='instructor',
            name='courses',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to='courses_available.courses'),
        ),
    ]
