# Generated by Django 4.0.6 on 2022-07-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_available', '0001_initial'),
        ('users', '0013_remove_instructor_courses_instructor_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='courses',
        ),
        migrations.AddField(
            model_name='instructor',
            name='courses',
            field=models.ManyToManyField(blank=True, to='courses_available.courses'),
        ),
    ]
