# Generated by Django 4.0.6 on 2022-07-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_student_courses'),
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='course',
        ),
        migrations.AddField(
            model_name='grade',
            name='course',
            field=models.ManyToManyField(to='users.course'),
        ),
    ]
