# Generated by Django 4.0.6 on 2022-07-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_remove_grade_course_grade_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='course',
        ),
        migrations.AddField(
            model_name='grade',
            name='course',
            field=models.CharField(default='XXX100', max_length=6),
        ),
    ]
