# Generated by Django 4.0.6 on 2022-07-20 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_remove_grade_course_grade_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='course',
            field=models.CharField(default='AAAXXX', max_length=6),
        ),
    ]
