# Generated by Django 4.0.6 on 2022-07-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='lecture_notes'),
        ),
    ]
