# Generated by Django 4.0.6 on 2022-07-28 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
